tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "shyiko/kubesec"
tap "universal-ctags/universal-ctags"
brew "anyenv"
brew "archey"
brew "ascii"
brew "bash"
brew "bat"
brew "bluetoothconnector"
brew "boost"
brew "openssl@1.1"
brew "sqlite"
brew "glib"
brew "cairo"
brew "circleci"
brew "cliclick"
brew "cmake"
brew "coreutils"
brew "cowsay"
brew "curl"
brew "docutils"
brew "figlet"
brew "firebase-cli"
brew "fortune"
brew "fswatch"
brew "fzf"
brew "ghq"
brew "git"
brew "gnu-sed"
brew "harfbuzz"
brew "graphviz"
brew "htop"
brew "imagemagick"
brew "inetutils"
brew "jq"
brew "kubectx"
brew "kustomize"
brew "lazygit"
brew "lftp"
brew "libevent"
brew "markdown"
brew "mas"
brew "mycli"
brew "mysql@5.7", restart_service: true
brew "nginx"
brew "nkf"
brew "pre-commit"
brew "protobuf"
brew "prototool"
brew "pulumi"
brew "redis"
brew "ripgrep"
brew "rsync"
brew "ruby"
brew "skaffold"
brew "starship"
brew "stern"
brew "telnet"
brew "tfenv"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "translate-shell"
brew "tree"
brew "unison"
brew "vim"
brew "yamllint"
brew "yarn"
brew "shyiko/kubesec/kubesec"
cask "adoptopenjdk"
cask "alacritty"
cask "ngrok"
mas "1Password 7", id: 1333542190
mas "Bear", id: 1091189122
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
