#!/bin/bash
#
# Export installed Claude Code plugins to plugins.txt
#
# Usage: ./export-plugins.sh [--stdout]
#
# Options:
#   --stdout  Print to stdout instead of updating plugins.txt
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_LIST="${SCRIPT_DIR}/plugins.txt"
INSTALLED_JSON="${HOME}/.claude/plugins/installed_plugins.json"

TO_STDOUT=false
if [[ "${1:-}" == "--stdout" ]]; then
    TO_STDOUT=true
fi

if [[ ! -f "$INSTALLED_JSON" ]]; then
    echo "Error: installed_plugins.json not found: $INSTALLED_JSON"
    exit 1
fi

# Check if jq is available
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed."
    echo "Install with: brew install jq"
    exit 1
fi

# Extract user-scoped plugins from installed_plugins.json
# Format: marketplace/plugin-name (from "plugin-name@marketplace" keys where scope=user)
extract_plugins() {
    jq -r '
        .plugins | to_entries[] |
        select(.value[0].scope == "user") |
        .key |
        split("@") |
        "\(.[1])/\(.[0])"
    ' "$INSTALLED_JSON" | sort
}

generate_output() {
    cat << 'EOF'
# Claude Code Plugin List
# Format: marketplace/plugin-name[@version]
# Lines starting with # are ignored
#
# Install: ~/.claude/plugins/install-plugins.sh
# Export:  ~/.claude/plugins/export-plugins.sh
#
# Auto-generated by export-plugins.sh
# Manual edits will be preserved if you re-run export with care

EOF

    echo "# === User-scoped Plugins ==="
    extract_plugins
}

if $TO_STDOUT; then
    generate_output
else
    # Backup existing file
    if [[ -f "$PLUGIN_LIST" ]]; then
        cp "$PLUGIN_LIST" "${PLUGIN_LIST}.bak"
        echo "Backed up existing plugins.txt to plugins.txt.bak"
    fi

    generate_output > "$PLUGIN_LIST"
    echo "Exported plugins to: $PLUGIN_LIST"
    echo ""
    echo "Plugins found:"
    extract_plugins | sed 's/^/  /'
fi
